version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 🟢 Persistent data storage

  user_app:
    build:
      context: ./ 
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - 3000:3001
    depends_on:
      - postgres

# 🧱 Named volume declared here
volumes:
  postgres_data: